import type { Metadata } from "next";
import { connection } from "next/server";
import "@fontsource-variable/inter";
import "@fontsource-variable/newsreader";
import "flag-icons/css/flag-icons.min.css";
import { siteMetadata } from "@/lib/site-metadata";
import "./globals.css";

export const metadata: Metadata = siteMetadata;

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Per-request nonces cannot be injected into prerendered HTML. Opt the whole
  // application tree into request-time rendering so public and authenticated
  // documents receive the nonce generated by middleware.
  await connection();
  return (
    <html lang="en">
      <body>
        <a className="skip-link" href="#main-content">
          Skip to main content
        </a>
        {children}
      </body>
    </html>
  );
}
