"""Initial explicit Bumpa Bestie control-plane schema.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-12 02:40:07.946285
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp_sessions",
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_otp_sessions_expires_at"), "otp_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_otp_sessions_phone_e164"), "otp_sessions", ["phone_e164"], unique=False
    )
    op.create_table(
        "provider_webhook_events",
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("external_event_id", sa.String(length=160), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processing_status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_event_id"),
    )
    op.create_table(
        "tenants",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("business_category", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("research_consent_status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("primary_phone_e164", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_primary_phone_e164"), "users", ["primary_phone_e164"], unique=True
    )
    op.create_table(
        "audit_logs",
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=True),
        sa.Column("resource_id", sa.String(length=80), nullable=True),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("correlation_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_jti_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_token_jti_hash"), "auth_sessions", ["token_jti_hash"], unique=True
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "bumpa_connections",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=False),
        sa.Column("scope_type", sa.String(length=24), nullable=False),
        sa.Column("scope_id", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("last_successful_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failed_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id"),
    )
    op.create_index(
        op.f("ix_bumpa_connections_tenant_id"), "bumpa_connections", ["tenant_id"], unique=False
    )
    op.create_table(
        "bumpa_orders",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("bumpa_order_id", sa.String(length=120), nullable=False),
        sa.Column("order_number", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=80), nullable=True),
        sa.Column("payment_status", sa.String(length=80), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("order_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "bumpa_order_id"),
    )
    op.create_index(op.f("ix_bumpa_orders_tenant_id"), "bumpa_orders", ["tenant_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conversation_tenant_updated", "conversations", ["tenant_id", "updated_at"], unique=False
    )
    op.create_table(
        "hermes_profiles",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("profile_name", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("api_internal_url", sa.String(length=300), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_name"),
        sa.UniqueConstraint("tenant_id"),
    )
    op.create_index(
        op.f("ix_hermes_profiles_tenant_id"), "hermes_profiles", ["tenant_id"], unique=False
    )
    op.create_table(
        "mcp_connections",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("encrypted_credentials", sa.Text(), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column("admin_approved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mcp_connections_tenant_id"), "mcp_connections", ["tenant_id"], unique=False
    )
    op.create_table(
        "phone_identities",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column("whatsapp_wa_id", sa.String(length=40), nullable=True),
        sa.Column("label", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("opt_out", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("whatsapp_wa_id"),
    )
    op.create_index(
        op.f("ix_phone_identities_phone_e164"), "phone_identities", ["phone_e164"], unique=True
    )
    op.create_index(
        op.f("ix_phone_identities_tenant_id"), "phone_identities", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_phone_identities_user_id"), "phone_identities", ["user_id"], unique=False
    )
    op.create_table(
        "platform_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role"),
    )
    op.create_index(op.f("ix_platform_roles_role"), "platform_roles", ["role"], unique=False)
    op.create_index(op.f("ix_platform_roles_user_id"), "platform_roles", ["user_id"], unique=False)
    op.create_table(
        "research_consent_history",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_consent_history_tenant_id"),
        "research_consent_history",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "research_reports",
        sa.Column("report_type", sa.String(length=80), nullable=False),
        sa.Column("generated_by", sa.String(length=36), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["generated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_errors",
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("service", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id"),
    )
    op.create_index(
        op.f("ix_tenant_memberships_tenant_id"), "tenant_memberships", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_memberships_user_id"), "tenant_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "usage_events",
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("units", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "whatsapp_messages",
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("meta_message_id", sa.String(length=160), nullable=True),
        sa.Column("wa_id", sa.String(length=40), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("message_type", sa.String(length=40), nullable=True),
        sa.Column("text_body", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_whatsapp_messages_meta_message_id"),
        "whatsapp_messages",
        ["meta_message_id"],
        unique=True,
    )
    op.create_table(
        "agent_messages",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("hermes_profile_id", sa.String(length=36), nullable=True),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=24), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("redacted_content", sa.Text(), nullable=True),
        sa.Column("external_message_id", sa.String(length=160), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hermes_profile_id"], ["hermes_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "external_message_id"),
    )
    op.create_index(
        "ix_message_tenant_conversation_created",
        "agent_messages",
        ["tenant_id", "conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "artifacts",
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("format", sa.String(length=12), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["research_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "format"),
    )
    op.create_table(
        "bumpa_sync_runs",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("bumpa_connection_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("requested_from", sa.Date(), nullable=False),
        sa.Column("requested_to", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("dataset_results", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["bumpa_connection_id"], ["bumpa_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bumpa_sync_runs_status"), "bumpa_sync_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_bumpa_sync_runs_tenant_id"), "bumpa_sync_runs", ["tenant_id"], unique=False
    )
    op.create_table(
        "whatsapp_delivery_events",
        sa.Column("whatsapp_message_id", sa.String(length=36), nullable=True),
        sa.Column("meta_message_id", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("event_timestamp", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["whatsapp_message_id"], ["whatsapp_messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meta_message_id", "status", "event_timestamp"),
    )
    op.create_index(
        op.f("ix_whatsapp_delivery_events_meta_message_id"),
        "whatsapp_delivery_events",
        ["meta_message_id"],
        unique=False,
    )
    op.create_table(
        "bumpa_metric_snapshots",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("sync_run_id", sa.String(length=36), nullable=False),
        sa.Column("metric_key", sa.String(length=120), nullable=False),
        sa.Column("metric_title", sa.String(length=200), nullable=True),
        sa.Column("value_decimal", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("requested_from", sa.Date(), nullable=False),
        sa.Column("requested_to", sa.Date(), nullable=False),
        sa.Column("availability", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["sync_run_id"], ["bumpa_sync_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_tenant_key_created",
        "bumpa_metric_snapshots",
        ["tenant_id", "metric_key", "created_at"],
        unique=False,
    )
    op.create_table(
        "bumpa_raw_responses",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("sync_run_id", sa.String(length=36), nullable=False),
        sa.Column("resource", sa.String(length=80), nullable=False),
        sa.Column("dataset", sa.String(length=80), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("availability", sa.String(length=24), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("pii_level", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["sync_run_id"], ["bumpa_sync_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bumpa_raw_responses_tenant_id"), "bumpa_raw_responses", ["tenant_id"], unique=False
    )
    op.create_table(
        "research_events",
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("agent_message_id", sa.String(length=36), nullable=True),
        sa.Column("channel", sa.String(length=24), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("redacted_text", sa.Text(), nullable=True),
        sa.Column("primary_intent", sa.String(length=80), nullable=True),
        sa.Column("business_function", sa.String(length=80), nullable=True),
        sa.Column("ai_help_type", sa.String(length=80), nullable=True),
        sa.Column("complexity", sa.String(length=80), nullable=True),
        sa.Column("bumpa_data_used", sa.String(length=80), nullable=True),
        sa.Column("classification_version", sa.String(length=40), nullable=True),
        sa.Column("outcome", sa.JSON(), nullable=False),
        sa.Column("pii_redacted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["agent_message_id"], ["agent_messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_events_primary_intent"),
        "research_events",
        ["primary_intent"],
        unique=False,
    )
    op.create_index(
        "ix_research_filters",
        "research_events",
        ["tenant_id", "channel", "primary_intent", "created_at"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        tenant_tables = (
            "audit_logs",
            "bumpa_connections",
            "bumpa_metric_snapshots",
            "bumpa_orders",
            "bumpa_raw_responses",
            "bumpa_sync_runs",
            "conversations",
            "hermes_profiles",
            "mcp_connections",
            "phone_identities",
            "research_consent_history",
            "research_events",
            "system_errors",
            "tenant_memberships",
            "usage_events",
            "whatsapp_messages",
            "agent_messages",
        )
        predicate = (
            "current_setting('app.is_privileged', true) = 'true' OR "
            "tenant_id::text = nullif(current_setting('app.current_tenant_id', true), '')"
        )
        for table in tenant_tables:
            op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
            op.execute(
                f'CREATE POLICY tenant_isolation ON "{table}" '
                f"USING ({predicate}) WITH CHECK ({predicate})"
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_research_filters", table_name="research_events")
    op.drop_index(op.f("ix_research_events_primary_intent"), table_name="research_events")
    op.drop_table("research_events")
    op.drop_index(op.f("ix_bumpa_raw_responses_tenant_id"), table_name="bumpa_raw_responses")
    op.drop_table("bumpa_raw_responses")
    op.drop_index("ix_metric_tenant_key_created", table_name="bumpa_metric_snapshots")
    op.drop_table("bumpa_metric_snapshots")
    op.drop_index(
        op.f("ix_whatsapp_delivery_events_meta_message_id"), table_name="whatsapp_delivery_events"
    )
    op.drop_table("whatsapp_delivery_events")
    op.drop_index(op.f("ix_bumpa_sync_runs_tenant_id"), table_name="bumpa_sync_runs")
    op.drop_index(op.f("ix_bumpa_sync_runs_status"), table_name="bumpa_sync_runs")
    op.drop_table("bumpa_sync_runs")
    op.drop_table("artifacts")
    op.drop_index("ix_message_tenant_conversation_created", table_name="agent_messages")
    op.drop_table("agent_messages")
    op.drop_index(op.f("ix_whatsapp_messages_meta_message_id"), table_name="whatsapp_messages")
    op.drop_table("whatsapp_messages")
    op.drop_table("usage_events")
    op.drop_index(op.f("ix_tenant_memberships_user_id"), table_name="tenant_memberships")
    op.drop_index(op.f("ix_tenant_memberships_tenant_id"), table_name="tenant_memberships")
    op.drop_table("tenant_memberships")
    op.drop_table("system_errors")
    op.drop_table("research_reports")
    op.drop_index(
        op.f("ix_research_consent_history_tenant_id"), table_name="research_consent_history"
    )
    op.drop_table("research_consent_history")
    op.drop_index(op.f("ix_platform_roles_user_id"), table_name="platform_roles")
    op.drop_index(op.f("ix_platform_roles_role"), table_name="platform_roles")
    op.drop_table("platform_roles")
    op.drop_index(op.f("ix_phone_identities_user_id"), table_name="phone_identities")
    op.drop_index(op.f("ix_phone_identities_tenant_id"), table_name="phone_identities")
    op.drop_index(op.f("ix_phone_identities_phone_e164"), table_name="phone_identities")
    op.drop_table("phone_identities")
    op.drop_index(op.f("ix_mcp_connections_tenant_id"), table_name="mcp_connections")
    op.drop_table("mcp_connections")
    op.drop_index(op.f("ix_hermes_profiles_tenant_id"), table_name="hermes_profiles")
    op.drop_table("hermes_profiles")
    op.drop_index("ix_conversation_tenant_updated", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_bumpa_orders_tenant_id"), table_name="bumpa_orders")
    op.drop_table("bumpa_orders")
    op.drop_index(op.f("ix_bumpa_connections_tenant_id"), table_name="bumpa_connections")
    op.drop_table("bumpa_connections")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_token_jti_hash"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_primary_phone_e164"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("provider_webhook_events")
    op.drop_index(op.f("ix_otp_sessions_phone_e164"), table_name="otp_sessions")
    op.drop_index(op.f("ix_otp_sessions_expires_at"), table_name="otp_sessions")
    op.drop_table("otp_sessions")
    # ### end Alembic commands ###
